# FROM node:lts-alpine
FROM node:bullseye-slim

WORKDIR /usr/src/app

ENV NODE_ENV=production

COPY package.json .

COPY package-lock.json .

RUN npm install

COPY . .

EXPOSE ${PORT}

RUN npx prisma generate

CMD [ "node", "src/index.js" ]